In [1]:
#import relevant libraries
import numpy as np
from sklearn.model_selection import train_test_split

In [13]:
a = np.arange(1,101)

In [15]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [19]:
#split data
train_test_split(a)

[array([66, 47, 97, 82, 96, 94, 89, 88, 76, 23, 93, 69,  2, 34, 20, 92, 81,
        38, 45, 31, 19, 91, 53, 75, 43, 21, 11, 59, 65, 55, 67, 99, 64, 27,
        35, 54, 52, 39, 77, 80,  3,  6, 48, 13, 90, 85, 95, 26, 58,  5,  7,
        15,  4, 29, 78, 86, 62, 37,  9, 12, 25, 60, 56, 71, 50, 74, 61, 49,
        98, 32, 87, 28, 70, 46, 40]),
 array([ 14,  44,  51,  57,  33,  84,  24,  18,  16,  68,  36,  42,  41,
         63,  73, 100,  22,  30,   1,   8,  83,  72,  17,  10,  79])]

In [46]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size= 0.2) #shuffle = False, random_state = 365

In [48]:
a_train.shape, a_test.shape

((80,), (20,))

In [50]:
a_train

array([ 98,  42,  71,  61,  21,  67,  23,  85,  59,  87,  34,  36,  51,
        15,   3,  73,  99,  62,  16,  79,  14,  47,  66,   9,  27,  81,
        37,  46,  31,   4,  95,  39,  13,  40,  24,   7,  83,  82,  58,
        49,  75,  69,  72,  90,  77,  89,  28,  86,  10,  60,  94,  17,
        33,  35, 100,  76,  52,   8,   2,  29,  44,  80,  64,  74,  48,
        96,  91,  78,   1,  18,  92,  30,  88,  50,  53,  63,  32,  25,
         5,  45])

In [52]:
a_test

array([56, 54, 41, 11, 97, 12, 57, 22, 19, 55, 43, 68, 65, 93,  6, 26, 70,
       20, 38, 84])

In [54]:
b_train.shape, b_test.shape

((80,), (20,))

In [56]:
b_train

array([598, 542, 571, 561, 521, 567, 523, 585, 559, 587, 534, 536, 551,
       515, 503, 573, 599, 562, 516, 579, 514, 547, 566, 509, 527, 581,
       537, 546, 531, 504, 595, 539, 513, 540, 524, 507, 583, 582, 558,
       549, 575, 569, 572, 590, 577, 589, 528, 586, 510, 560, 594, 517,
       533, 535, 600, 576, 552, 508, 502, 529, 544, 580, 564, 574, 548,
       596, 591, 578, 501, 518, 592, 530, 588, 550, 553, 563, 532, 525,
       505, 545])

In [58]:
b_test

array([556, 554, 541, 511, 597, 512, 557, 522, 519, 555, 543, 568, 565,
       593, 506, 526, 570, 520, 538, 584])